### ISSUE TITLE
请问为什么插件有时候可以运行查出单词意思，但有时候会显示错误

### ISSUE THREAD

**Issue by 1ynzzy** [sirius-fan/FastWordQuery#14]
![%Q6E}GP6P@CNG %GGIS@0EN](https://github.com/sirius-fan/FastWordQuery/assets/69032662/49c45c4d-f679-4233-bd12-dce4f6f7ac88)

如图

错误
运行出错。请在启动Anki时按住「Shift」键以临时禁用插件加载。 如仅在插件启用时出错，请使用「工具」>「插件」功能禁用部分插件后重启Anki，请重复上述步骤找出引起错误的插件并反馈给插件作者。 调试信息：
Anki 2.1.66 (70506aeb) Python 3.9.15 Qt 6.5.2 PyQt 6.5.2
Platform: Windows-10-10.0.19041
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-08-27 17:11:50
相关插件：⁨FastWordQuery-Qt6⁩

Caught exception:
Traceback (most recent call last):
  File "C:\Users\Lynzzy\AppData\Roaming\Anki2\addons21\103636257\common.py", line 80, in <lambda>
    action.triggered.connect(lambda: query_from_browser(browser))
  File "C:\Users\Lynzzy\AppData\Roaming\Anki2\addons21\103636257\query\__init__.py", line 57, in query_from_browser
    query_all(notes)
  File "C:\Users\Lynzzy\AppData\Roaming\Anki2\addons21\103636257\query\__init__.py", line 117, in query_all
    promot_choose_css(work_manager.missed_css)
  File "C:\Users\Lynzzy\AppData\Roaming\Anki2\addons21\103636257\query\common.py", line 128, in promot_choose_css
    Template.miss_css.format(dict=css['title'], css=css['file']))
AttributeError: type object 'Template' has no attribute 'miss_css'

对这方面实在不懂一窍不通 看不懂为什么报错 麻烦大佬看

用的这两个词典
链接: https://pan.baidu.com/s/1k4329sDMCv7knv1uNyhTgQ?pwd=6h4i 提取码: 6h4i 
链接: https://pan.baidu.com/s/1fjLn6fROIqSLs5LKQ8A9hw?pwd=8r8k 提取码: 8r8k

**Comment by sirius-fan** [comment]
有点奇怪，知道是查哪个词时候出的问题吗

**Comment by 1ynzzy** [comment]
> 有点奇怪，知道是查哪个词时候出的问题吗

基本所有词都是这样，单独添加一个词语的时候，按查询按钮第一遍会查不出意思也不会报错，第二遍就会报错但报错同时又可以正常查出词语意思。批量查词的时候按一次就可以查出意思但 同时也会报错。

**Comment by sirius-fan** [comment]
我下载了上面牛津9的词典，查了5000个词没有复现，你能提供下你的牌组吗，导出时**不勾选** 包含媒体文件和兼容旧版ANKI，

还有，在你那用牛津9也是有问题的吧，另一个词典太大了，度盘太慢我就不测了
