### ISSUE TITLE
anki升级后插件报错

### ISSUE THREAD

**Issue by SOREMUZ** [sirius-fan/FastWordQuery#18]
大佬好久不见，最近anki升级了23.10，插件报错啦

Quite a few add-ons will need updates to support the Qt 6 version of this release. Some [porting notes](https://forums.ankiweb.net/t/porting-tips-for-anki-23-10/35916) are available.

错误
运行出错。请在启动 Anki 时按住 Shift 键以临时禁用插件加载。 如仅在插件启用时出错，请使用「工具」>「插件」功能禁用部分插件后重启 Anki，请重复上述步骤找出引起错误的插件并反馈给插件作者。 调试信息：
Anki 23.10 (51a10f09) Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-13.2.1-arm64-arm-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-11-03 23:02:07
相关插件：⁨FastWordQuery-Qt6⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.progress", line 118, in handler
  File "aqt.main", line 218, in on_window_init
  File "aqt.main", line 317, in setupProfile
  File "aqt.main", line 496, in loadProfile
  File "_aqt.hooks", line 4107, in __call__
  File "anki.hooks", line 34, in runHook
  File "/Users/chikane/Library/Application Support/Anki2/addons21/103636257/__init__.py", line 37, in start_here
    from . import common as fastwq
  File "/Users/chikane/Library/Application Support/Anki2/addons21/103636257/common.py", line 29, in <module>
    from .gui import show_about_dialog, show_options  # , check_updates
  File "/Users/chikane/Library/Application Support/Anki2/addons21/103636257/gui/__init__.py", line 3, in <module>
    from .common import *
  File "/Users/chikane/Library/Application Support/Anki2/addons21/103636257/gui/common.py", line 31, in <module>
    from .options import OptionsDialog
  File "/Users/chikane/Library/Application Support/Anki2/addons21/103636257/gui/options.py", line 25, in <module>
    import sip
ModuleNotFoundError: No module named 'sip'

**Comment by sirius-fan** [comment]
已修复，更新，或者重新安装即可
