### ISSUE TITLE
ModuleNotFoundError: No module named 'sip'

### ISSUE THREAD

**Issue by chenkeao** [sirius-fan/FastWordQuery#19]
**环境 （请填写以下信息）：**
 - 操作系统: Linux-6.5.9-arch2-1-x86_64-with-glibc2.38
 - Anki 版本: Anki 23.10 (51a10f0) Python 3.11.5 Qt 6.6.0 PyQt 6.6.0

**描述错误**
ModuleNotFoundError: No module named 'sip'

**复现**
每次启动时

**附加上下文**
运行出错。请在启动 Anki 时按住 Shift 键以临时禁用插件加载。 如仅在插件启用时出错，请使用「工具」>「插件」功能禁用部分插件后重启 Anki，请重复上述步骤找出引起错误的插件并反馈给插件作者。 调试信息：
Anki 23.10 (51a10f0) Python 3.11.5 Qt 6.6.0 PyQt 6.6.0
Platform: Linux-6.5.9-arch2-1-x86_64-with-glibc2.38
Flags: frz=False ao=True sv=3
Add-ons, last update check: 2023-11-06 07:25:08
相关插件：⁨FastWordQuery-Qt6⁩

Caught exception:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/aqt/progress.py", line 118, in handler
    func()
  File "/usr/lib/python3.11/site-packages/aqt/main.py", line 218, in on_window_init
    fn()
  File "/usr/lib/python3.11/site-packages/aqt/main.py", line 317, in setupProfile
    self.loadProfile()
  File "/usr/lib/python3.11/site-packages/aqt/main.py", line 496, in loadProfile
    gui_hooks.profile_did_open()
  File "/usr/lib/python3.11/site-packages/_aqt/hooks.py", line 3323, in __call__
    anki.hooks.runHook("profileLoaded")
  File "/usr/lib/python3.11/site-packages/anki/hooks.py", line 34, in runHook
    func(*args)
  File "/home/momo/.local/share/Anki2/addons21/103636257/__init__.py", line 37, in start_here
    from . import common as fastwq
  File "/home/momo/.local/share/Anki2/addons21/103636257/common.py", line 29, in <module>
    from .gui import show_about_dialog, show_options  # , check_updates
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/momo/.local/share/Anki2/addons21/103636257/gui/__init__.py", line 3, in <module>
    from .common import *
  File "/home/momo/.local/share/Anki2/addons21/103636257/gui/common.py", line 31, in <module>
    from .options import OptionsDialog
  File "/home/momo/.local/share/Anki2/addons21/103636257/gui/options.py", line 25, in <module>
    import sip
ModuleNotFoundError: No module named 'sip'

**Comment by chenkeao** [comment]
根据错误信息修改`import sip`为`from PyQt6 import sip`后启动时就不报错了

**Comment by sirius-fan** [comment]
fixed
