### ISSUE TITLE
请问这个错误如何修复呀？

### ISSUE THREAD

**Issue by mengjiacupl** [sirius-fan/FastWordQuery#5]
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.64 (581f82c5) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: macOS-13.2-arm64-arm-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-06-09 03:24:45
Add-ons possibly involved: ⁨fastwq⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/mengjia/Library/Application Support/Anki2/addons21/fastwq/gui/options.py", line 212, in accept
    self.save()
  File "/Users/mengjia/Library/Application Support/Anki2/addons21/fastwq/gui/options.py", line 322, in save
    config.update(data)
  File "/Users/mengjia/Library/Application Support/Anki2/addons21/fastwq/context.py", line 60, in update
    with open(self.path, 'w', encoding='utf-8') as f:
PermissionError: [Errno 1] Operation not permitted: '_fastwqcfg.json'

**Comment by sirius-fan** [comment]
看起来是权限问题，怎么触发的，打开就是吗
